config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tiny_homes do
    resources :bookings, only: :create
    resources :home_amenities, only: [:new, :create, :edit, :update]
  end

  get '/my_tiny_homes', to: 'tiny_homes#my_index'

  resources :bookings, only: [:index, :show, :destroy, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:edit, :update, :destroy]

  resources :home_amenities, only: :destroy
end


# /tiny_homes GET tiny_homes  index

# /tiny_homes/new GET tiny_homes  new
# /tiny_homes POST  tiny_homes  create

# /tiny_homes/:id GET tiny_homes  show

# /tiny_homes/:id/edit  GET tiny_homes  edit
# /tiny_homes/:id/  PATCH tiny_homes  update

# /tiny_homes/:id/  DELETE  tiny_homes  destroy

# /tiny_homes/:id/bookings/new  GET bookings  new
# /tiny_homes/:id/bookings  POST  bookings  create

# /bookings/:id GET bookings  show

# /tiny_homes/:id/bookings/:id/edit GET bookings  edit
# /tiny_homes/:id/bookings/:id  PATCH bookings  update

# /bookings/:id DELETE  bookings  destroy

# /tiny_homes/:id/home_amenities/new  GET home_amenities  new
# /tiny_homes/:id/home_amenities  POST  home_amenities  create

# /tiny_homes/:id/home_amenities/:id/edit GET home_amenities  edit
# /tiny_homes/:id/home_amenities/:id  PATCH home_amenities  update

# home_amenities/:id  DELETE  home_amenities  destroy

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :tiny_home
  belongs_to :user
  has_one :review, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true, after_date: :start_date

  def total_cost
    (self.end_date - self.start_date).to_i * self.tiny_home.price
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    # @bookings = Booking.all
    @bookings = policy_scope(Booking).where(user: current_user).order(created_at: :desc)
  end

  def show
    @review = Review.find_by(booking_id: @booking.id)
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.tiny_home_id = params[:tiny_home_id]
    @booking.user = current_user
    @tiny_home = TinyHome.find(params[:tiny_home_id])
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking), notice: 'Your booking was successfully completed.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params) && current_user == @booking.user
      redirect_to bookings_path, notice: 'Your booking was successfully updated.'
    elsif @booking.update(booking_params)
      redirect_to my_tiny_homes_path, notice: 'Your request was successfully approved.'
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, notice: 'Your booking was successfully cancelled.'
  end

  def approved!
    @approved = true
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :tiny_home_id, :user_id, :approved)
  end
end

app/views/bookings/_form.html.erb
<!-- <div class="container">
  <div class="row justify-content-center py-4">
    <div class="col-6"> -->
<!--       <%#= simple_form_for [@tiny_home, @booking] do |f| %>

        <div class="form-inputs my-3">
          <%#= f.input :start_date %>
          <%#= f.input :end_date %>
        </div>

        <div class="form-actions mb-4">
          <%#= f.button :submit, class: 'btn btn-secondary' %>
        </div>
      <%# end %> -->

      <%= simple_form_for [@tiny_home, @booking] do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.button :submit, "Go", class: "btn btn-secondary" %>
      <% end %>
<!--     </div>
  </div>
</div> -->

app/views/bookings/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <h1>Edit Your Stay at <%= @booking.tiny_home.name %></h1>
      <%= render 'form' %>
      <p class="my-2"><%= link_to 'Back', booking_path(@booking) %></p>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <h1>My bookings</h1>
  <% @bookings.each do |booking| %>

    <div class="card-booking">
      <% if booking.tiny_home.photos[0].present?%>
        <%= cl_image_tag booking.tiny_home.photos[0].key, crop: :fill %>
      <% else %>
        <img src="https://thelittlerebellion.com/wp-content/uploads/Sojourner-1-881x589-1.jpg" />
      <% end %>
      <div class="card-booking-infos d-flex">
        <div class="row">
          <div class="col-6 ">
            <h2><strong><%= link_to booking.tiny_home.name, booking_path(booking) %></strong></h2>
            <div>
              <p><%= booking.tiny_home.address %></p>
              <p>FROM <%= booking.start_date %> TO <%= booking.end_date %></p>
            </div>
          </div>
          <div class="col-6 text-right">
            <b>TOTAL: $<%= booking.total_cost %></b>
            <% if policy(booking).edit? %>
              <p class='pr-2'><%= link_to 'Edit', edit_booking_path(booking) %></p>
            <% end %>
            <% if policy(booking).destroy? %>
              <p class=''><%= link_to 'Delete', booking_path(booking), method: :delete %></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 my-4">
      <% if @booking.tiny_home.photos[0].present?%>
        <%= cl_image_tag @booking.tiny_home.photos[0].key, width: 400, crop: :fill %>
      <% else %>
        <img src="https://thelittlerebellion.com/wp-content/uploads/Sojourner-1-881x589-1.jpg" />
      <% end %>
      <h1><%= link_to @booking.tiny_home.name, tiny_home_path(@booking.tiny_home) %></h1>
      <p>FROM <%= @booking.start_date %> TO <%= @booking.end_date %></p>
      <b>TOTAL: $<%= @booking.total_cost %> </b>
      <p>status:
        <% if @booking.approved == false %>
          <em>pending</em>
        <% else %>
          <em>approved!</em>
        <% end %>
      </p>
    </div>
    <div class="col-8">
      <% if @review.nil? %>
        <%= link_to 'Add a review', new_booking_review_path(@booking), class: 'btn btn-secondary' %>
      <% end %>
      <% if policy(@booking).edit? %>
        <%= link_to 'Edit booking', edit_booking_path(@booking), class: 'btn btn-secondary' %>
      <% end %>
      <% if policy(@booking).destroy? %>
        <%= link_to 'Delete booking', booking_path(@booking), method: :delete, class: 'btn btn-secondary'  %>
      <% end %>
    </div>
  </div>
</div>

<% unless @review.nil? %>
  <div class="container">
    <div class="review">
      <p><b>My Review</b></p>
      <p><b>Comment:</b> <%= @booking.review.comment %></p>
      <p><b>Star:</b> <%= @booking.review.star %></p>

      <%= link_to 'Edit review', edit_review_path(@review), class: 'btn btn-secondary' %>

      <%= link_to 'Delete review', review_path(@review), method: :delete, class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>