config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tiny_homes do
    resources :bookings, only: :create
    resources :home_amenities, only: [:new, :create, :edit, :update]
  end

  get '/my_tiny_homes', to: 'tiny_homes#my_index'

  resources :bookings, only: [:index, :show, :destroy, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:edit, :update, :destroy]

  resources :home_amenities, only: :destroy
end


# /tiny_homes GET tiny_homes  index

# /tiny_homes/new GET tiny_homes  new
# /tiny_homes POST  tiny_homes  create

# /tiny_homes/:id GET tiny_homes  show

# /tiny_homes/:id/edit  GET tiny_homes  edit
# /tiny_homes/:id/  PATCH tiny_homes  update

# /tiny_homes/:id/  DELETE  tiny_homes  destroy

# /tiny_homes/:id/bookings/new  GET bookings  new
# /tiny_homes/:id/bookings  POST  bookings  create

# /bookings/:id GET bookings  show

# /tiny_homes/:id/bookings/:id/edit GET bookings  edit
# /tiny_homes/:id/bookings/:id  PATCH bookings  update

# /bookings/:id DELETE  bookings  destroy

# /tiny_homes/:id/home_amenities/new  GET home_amenities  new
# /tiny_homes/:id/home_amenities  POST  home_amenities  create

# /tiny_homes/:id/home_amenities/:id/edit GET home_amenities  edit
# /tiny_homes/:id/home_amenities/:id  PATCH home_amenities  update

# home_amenities/:id  DELETE  home_amenities  destroy

app/views/shared/_card.html.erb
  <div class="container">
    <div class="row justify-content-center">
      <% @tiny_homes.all.first(3).each do |th| %>
        <div class="col-12 col-lg-4">

          <%= link_to tiny_home_path(th) do %>
            <div class="card-trip">
              <% if th.photos[0].present?%>
                <%= cl_image_tag th.photos[0].key, crop: :fill %>
              <% else %>
                <img src="https://thelittlerebellion.com/wp-content/uploads/Sojourner-1-881x589-1.jpg" />
              <% end %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= th.name %></h2>
                  <p><%= th.description %></p>
                </div>
                <h2 class="card-trip-pricing">$<%= th.price %>/day</h2>
                <% if th.photos[0].present?%>
                  <%= cl_image_tag th.user.avatar.key, crop: :fill, class: 'card-trip-user avatar-bordered' %>
                <% else %>
                  <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fa fa-copyright">Wheelhouse</i>
  </div>
</div>

app/views/shared/_index_card.html.erb
  <!-- CARD -->
<div class="cards">
  <% @other_tiny_homes.each do |tiny_home| %>
    <div class="card_product">

      <%= link_to tiny_home_path(tiny_home) do %>
        <div class="card_product_item">
        <div class="card_product_image">
          <% if tiny_home.photos[0].present?%>
            <%= cl_image_tag tiny_home.photos[0].key, crop: :fill %>
          <% else %>
            <img src="https://thelittlerebellion.com/wp-content/uploads/Sojourner-1-881x589-1.jpg" />
          <% end %>
        </div>
        <div class="card_product_content">
          <div class="card_product_title">
            <div class="card_product_icon_text">
              <p><%= tiny_home.address %></p>
              <h2><%= tiny_home.name %></h2>
            </div>
            <div class="card_product_title_icon">
              <%= image_tag "icon-heart.svg"%>
            </div>
          </div>
          <div class="separator">
          </div>
          <div class="card_product_description">
            <p><%= tiny_home.description.capitalize %></p>
          </div>
          <div class="card_product_element">
            <div class="card_product_element_price">
              <h4 class="card_product_pricing">$<%= tiny_home.price %>/day</h4>
            </div>
          </div>
          <div class="d-flex card_product_element_details">
            <% if policy(tiny_home).edit? %>
              <p class='pr-2'><%= link_to 'Edit', edit_tiny_home_path(tiny_home) %></p>
            <% end %>
            <% if policy(tiny_home).destroy? %>
              <p class=''><%= link_to 'Delete', tiny_home_path(tiny_home), method: :delete %></p>
            <% end %>
          </div>
        </div>
        </div>
      <% end %>

    </div>
  <% end %>
</div>


            <!-- <div class="card_product_element_amenities"> -->
<!--               <ul>
                <%# @tiny_home.amenities.each do |amenity| %>
                  <li class="card_product_element_amenities_text">
                    <i class='<%#= amenity.icon %>'></i>
                    <p><%#= amenity.name.capitalize %></p>
                  </li>
                <%# end %>
              </ul> -->
            <!-- </div> -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon pl-5">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "wheelhouse_logo.png"%>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse px-5" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item active">
          <div class="container d-flex">
            <div class="row pr-3">
              <% unless controller_name == "pages" && action_name == "home" %>
                <%= form_tag tiny_homes_path, method: :get do %>
                  <%= text_field_tag :query,
                    params[:query],
                    class: "form-control",
                    id: 'tiny_home_address',
                    placeholder: "Location"
                  %>
              <% end %>
            </div>
            <div class="row pl-3">
                <%= submit_tag "Search", class: "btn btn-secondary" %>
            </div>
              <% end %>
          </div>
        </li>

        <li class="nav-item active px-5">

          <%= link_to "Tiny Homes", tiny_homes_path, class: "nav-link" %>
        </li>
        <li class="nav-item pr-3">
          <%= link_to "Add a Tiny Home", new_tiny_home_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-tiny-user avatar-bordered" />
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My tiny homes", my_tiny_homes_path, class: "dropdown-item" %>
            <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "My profile", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>